### ISSUE TITLE
Subscript Out of Bounds

### ISSUE THREAD

**Issue by silfornia** [ryurko/nflscrapR-data#3]
When executing season_play_by_play, getting a subscript out of bounds error. See attachment.

![unnamed](https://user-images.githubusercontent.com/32369650/30980853-70a4b322-a450-11e7-8294-5fa56e925b60.png)

**Comment by ryurko** [comment]
Please update nflscrapR, this was an error that occurred from the NFL creating empty URLs on gameday and the latest update should've addressed this.
