### ISSUE TITLE
Error in EPA and WPA on a muffed punt

### ISSUE THREAD

**Issue by guga31bb** [ryurko/nflscrapR-data#4]
GameID: 2017100808. 2nd quarter 12:36 left
Seattle punts, LA muffs punt, Seattle takes over. Pastebin of the datapoints: https://pastebin.com/ADrw1B6c

Seattle's expected points before is -1.558698 (makes sense, they're about to punt)
Expected points after is 4.058728 (makes sense, 1st and 10 from opponent 30)

So EPA should be 5.617426 (the difference between before and after) but instead it's listed as -2.50002953082569.

 home_wp_post is also different than home_wp_pre on the next line (I think it's home_wp_post that's wrong)

**Comment by ryurko** [comment]
This is fixed now, will update the data repository to reflect the updated package.
