### ISSUE TITLE
R Errors

### ISSUE THREAD

**Issue by silfornia** [ryurko/nflscrapR-data#6]
Hi,

When running the season stats script in R, I'm getting the following errors. Not sure if these are causing issues with the data. Also running very slow.

Note that I'm running this while the Thursday night game is being played. Not sure if that's part of it.

Thanks guys,
-Mike

TKIntRJMP.R version  5.05 
Warning: Loading required package: nnet
Warning: Loading required package: magrittr
Warning: Loading required package: XML
Warning: Loading required package: RCurl
Warning: Loading required package: bitops
Warning: Warning messages:
Warning: 1: In .parse_hms(..., order = "MS", quiet = quiet) :
Warning:   Some strings failed to parse, or all strings are NAs
Warning: 2: In .parse_hms(..., order = "MS", quiet = quiet) :
Warning:   Some strings failed to parse, or all strings are NAs
Warning: 3: In .parse_hms(..., order = "MS", quiet = quiet) :
Warning:   Some strings failed to parse, or all strings are NAs
Warning: 4: In .parse_hms(..., order = "MS", quiet = quiet) :
Warning:   Some strings failed to parse, or all strings are NAs
Warning: 5: In .parse_hms(..., order = "MS", quiet = quiet) :
Warning:   Some strings failed to parse, or all strings are NAs
Warning: 6: In .parse_hms(..., order = "MS", quiet = quiet) :
Warning:   Some strings failed to parse, or all strings are NAs
Warning: 7: In .parse_hms(..., order = "MS", quiet = quiet) :
Warning:   Some strings failed to parse, or all strings are NAs
Warning: 8: In .parse_hms(..., order = "MS", quiet = quiet) :
Warning:   Some strings failed to parse, or all strings are NAs
Warning: 9: In .parse_hms(..., order = "MS", quiet = quiet) :
Warning:   Some strings failed to parse, or all strings are NAs
Scriptable[]

**Comment by ryurko** [comment]
These are not errors, just a formatting warning. You don't need to worry about them, I'll add something to suppress them. Unfortunately running season_play_by_play() will take awhile (alot running behind the scenes!).
